print('jangan lupa makan asu')
print('aku adalah ultramen')
print('jangan lupa shalat')
print('jangan lupa ngaji')
print('ngegame aja gpp')
print('jangan lupa tidur')
print('jangan jadi beban keluarga')
print('nonton one piece biar tau apa artinya pertemanan')
print('belajar biar pinter')
print('harus sopan sama orng tua')